name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Npm Modules
      run: npm ci
    
    - name: Run All Test Suites
      run: npm test

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Export DB
      id: exportRequest
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://url00.herokuapp.com/admin/export'
        method: 'POST'
        data: '{"password":"${{ADMIN_PASSWORD}}"}'
    
    - name: Show DB
      run: echo ${{steps.exportRequest.outputs.response}}
      
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.8.9
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "url00"
        heroku_email: "mcpejs1@gmail.com"
      env:
        HD_ADMIN_PASSWORD: ${{secrets.ADMIN_PASSWORD}}

    - name: Import DB
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://url00.herokuapp.com/admin/import'
        method: 'POST'
        data: '{"password":"${{ADMIN_PASSWORD}}","list":"${{steps.exportRequest.outputs.response}}"}'
